### PR TITLE
Add effort to fix support for Javascript Plugin

### PR DESCRIPTION
**Pull request by julienarbey**
Add the possibility to set the effort to fix from the defined Cost like for the others plugins (Exemple : https://github.com/SonarCommunity/sonar-php/blob/master/sonar-php-plugin/src/main/java/org/sonar/plugins/php/PHPSquidSensor.java)

Sonar team, thank you so much for your amazing work !

### CODE REVIEW

**Comment by lindamartin** [comment]
@julienarbey Thanks a lot for you pull request but actually this issue has been fix in this commit: aafd1a831c185b4ed15705925dfa7a42bb10030e see [JavaScriptCheckContext.java#L115](https://github.com/SonarCommunity/sonar-javascript/commit/aafd1a831c185b4ed15705925dfa7a42bb10030e#diff-c1e0cbef0effd28b11f4beb9db5249c8R115). So I am closing this PR.
Thank you!

**Comment by julienarbey** [comment]
Sorry i did not saw that elena had previously made the change. Thank's

**Comment by lindamartin** [comment]
Please don't be sorry, it must had happened pretty much around the same time :)

**Comment by julienarbey** [comment]
Linda, do you have an idéa of when the new Javascript plugin version (2.8) will be released ?

**Comment by lindamartin** [comment]
@julienarbey yes I just updated Jira information about it see [Jira page](http://jira.sonarsource.com/browse/SONARJS/fixforversion/11911/). It should be released by the end of next week.

**Comment by julienarbey** [comment]
Great ! Good job !

Have a nice day or "Bonne journée" if you work in France (or Switzerland ;-))

**Pull request closed without merging**
